services: 
  db: 
    image: postgres:latest
    restart: unless-stopped
    ports: 
      - "${GOBID_DATABASE_PORT:-5432}:5432"
    environment: 
      POSTGRES_USER: ${GOBID_DATABASE_USER:-postgres}
      POSTGRES_PASSWORD: ${GOBID_DATABASE_PASSWORD:-postgres}
      POSTGRES_DB: ${GOBID_DATABASE_NAME:-postgres}
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local

